//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IHome.Server.Data
{
    public partial class base_permit_roledefine
    {
        #region Primitive Properties
    
        public virtual string city_id
        {
            get;
            set;
        }
    
        public virtual string city_name
        {
            get;
            set;
        }
    
        public virtual string company_id
        {
            get;
            set;
        }
    
        public virtual string company_name
        {
            get;
            set;
        }
    
        public virtual Nullable<sbyte> DefRole
        {
            get;
            set;
        }
    
        public virtual Nullable<sbyte> is_show
        {
            get;
            set;
        }
    
        public virtual string role_id
        {
            get;
            set;
        }
    
        public virtual string role_name
        {
            get;
            set;
        }

        #endregion
    }
}
