//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IHome.Server.Data
{
    public partial class base_datadic_detailinfo
    {
        #region Primitive Properties
    //
        public virtual Nullable<int> item_index
        {
            get;
            set;
        }
    //
        public virtual string item_key
        {
            get;
            set;
        }
    //
        public virtual string item_value
        {
            get;
            set;
        }
    //
        public virtual System.Guid record_id
        {
            get;
            set;
        }

        #endregion
    }
}
