//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IHome.Server.Data
{
    public partial class base_permit_define
    {
        #region Primitive Properties
    
        public virtual string permit_code
        {
            get;
            set;
        }
    
        public virtual string permit_id
        {
            get;
            set;
        }
    
        public virtual string permit_name
        {
            get;
            set;
        }
    
        public virtual string permit_roup
        {
            get;
            set;
        }

        #endregion
    }
}
