//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IHome.Server.Data
{
    public partial class base_community_buildinginfo
    {
        #region Primitive Properties
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual System.Guid building_id
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual Nullable<System.Guid> community_id
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual string building_name
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual string building_use
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual string building_type
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual Nullable<int> building_floor
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual Nullable<int> unit_num
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual string unit_type
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual string room_rule
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual string room_rule_remark
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual Nullable<int> status
        {
            get;
            set;
        }

        #endregion
    }
}
