//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IHome.Models.Data
{
    public partial class customer_traceinfo
    {
        #region Primitive Properties
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual System.Guid record_id
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual Nullable<System.Guid> customer_id
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual Nullable<int> trace_type
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual string trace_context
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual Nullable<System.DateTime> trace_time
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual string trace_person_id
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual string trace_person_name
        {
            get;
            set;
        }

        #endregion
    }
}
