//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IHome.Models.Data
{
    public partial class base_webpush_iteminfo
    {
        #region Primitive Properties
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual System.Guid record_id
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual Nullable<System.Guid> city_id
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual string city_name
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual string web_port_code
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual string web_port_name
        {
            get;
            set;
        }

        #endregion
    }
}
