//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IHome.Models.Data
{
    public partial class customer_baseinfo
    {
        #region Primitive Properties
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual System.Guid customer_id
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual string customer_name
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual string customer_sex
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual string mobile
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual string phone
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual string address
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual Nullable<int> status
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual string customer_type
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual Nullable<System.DateTime> last_trace_date
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual Nullable<System.Guid> add_person_id
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual Nullable<System.DateTime> add_time
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual Nullable<System.DateTime> update_time
        {
            get;
            set;
        }

        #endregion
    }
}
