//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IHome.Models.Data
{
    public partial class house_key_receiptioninfo
    {
        #region Primitive Properties
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual System.Guid record_id
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual Nullable<System.Guid> house_id
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual string house_code
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual string house_address
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual string receiption_code
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual Nullable<int> key_count
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual Nullable<System.DateTime> get_date
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual string customer_name
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual Nullable<System.Guid> get_person_id
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual string add_person_id
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual Nullable<System.DateTime> add_time
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual Nullable<System.DateTime> update_time
        {
            get;
            set;
        }
    
    	/// <summary>
    	///undefine	
    	/// </summary>
        public virtual Nullable<int> status
        {
            get;
            set;
        }

        #endregion
    }
}
